apiVersion: v1
kind: Pod
metadata:
  name: spring-boot-web
spec:
  containers:
    - image: 'rkp201/k8s-spring-app:1.3'
      name: spring-boot-web
      livenessProbe
        httpGet:
          path: /health
          port: 8080
      ports:
        - containerPort: 8080
          protocol: TCP
