apiVersion: v1
kind: Pod
metadata:
  name: spring-boot-web
spec:
  containers:
    - image: rkp201/k8s-spring-app:1.2
      name: spring-boot-web
      ports:
        - containerPort: 8080
          protocol: TCP
